# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  numberclassificationapi:
    image: numberclassificationapi
    build:
      context: .
      dockerfile: NumberClassificationApi/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 7177:7177
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
